[[redirects]]
  from = "/status"
  to = "https://stats.uptimerobot.com/lMVyrUoqYq"
  status = 301
  force = true

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true
  
[build.processing.images]
  compress = true