[[redirects]]
  from = "/status"
  to = "https://stats.uptimerobot.com/lMVyrUoqYq"
  status = 301
  force = true

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = false

[build.processing.js]
  bundle = true
  minify = false

[build.processing.html]
  pretty_urls = true
  
[build.processing.images]
  compress = true