const HOST="https://japanterebi.vercel.app/japanterebi";async function appendInvite(a){let c=document.createElement("invite");c.innerText=a;document.getElementById("invitesList").appendChild(c)}window.onload=()=>{reload();reloadAnnouncement()};
async function reload(){fetch(HOST+"/invites?token="+localStorage.getItem("__japanterebi_auth")).then(a=>a.json()).then(a=>{if(a.success){for(;document.getElementById("invitesList").firstChild;)document.getElementById("invitesList").removeChild(document.getElementById("invitesList").firstChild);for(index in a.data)appendInvite(a.data[index])}else"AUTH_ERROR"==a.error?newError("You don't seem to be correctly logged in"):newError("An error occured")})}
async function add(){fetch(HOST+"/invites?token="+localStorage.getItem("__japanterebi_auth")+"&new=true").then(a=>a.json()).then(a=>{if(a.success){for(newSuccess("Successfully created an invite");document.getElementById("invitesList").firstChild;)document.getElementById("invitesList").removeChild(document.getElementById("invitesList").firstChild);for(index in a.data)appendInvite(a.data[index])}else"AUTH_ERROR"==a.error?newError("You don't seem to be correctly logged in"):newError("An error occured")})}
async function submitAnnouncement(){let a="";""!=document.getElementById("currentAnnouncement").value&&(a+="&message="+encodeURIComponent(document.getElementById("currentAnnouncement").value));""!=document.getElementById("enAnnouncement").value&&(a+="&en="+encodeURIComponent(document.getElementById("enAnnouncement").value));""!=document.getElementById("frAnnouncement").value&&(a+="&fr="+encodeURIComponent(document.getElementById("frAnnouncement").value));""!=document.getElementById("jaAnnouncement").value&&
(a+="&ja="+encodeURIComponent(document.getElementById("jaAnnouncement").value));""!=document.getElementById("persistentAnnouncement").value&&(a+="&persistent="+encodeURIComponent(document.getElementById("persistentAnnouncement").value));fetch(HOST+"/announcement/new?token="+localStorage.getItem("__japanterebi_auth")+a).then(c=>c.json()).then(c=>{c.success?newSuccess("Successfully added a new announcement"):"AUTH_ERROR"==c.error?newError("You don't seem to be correctly logged in"):newError("An error occured")})}
async function resetAnnouncement(){fetch(HOST+"/announcement/reset?token="+localStorage.getItem("__japanterebi_auth")).then(a=>a.json()).then(a=>{a.success?(newSuccess("Successfully reset the announcement"),document.getElementById("currentAnnouncement").value="",document.getElementById("enAnnouncement").value="",document.getElementById("frAnnouncement").value="",document.getElementById("jaAnnouncement").value="",document.getElementById("persistentAnnouncement").value=""):"AUTH_ERROR"==a.error?newError("You don't seem to be correctly logged in"):
newError("An error occured")})}
async function reloadAnnouncement(){fetch(HOST+"/announcement?token="+localStorage.getItem("__japanterebi_auth")).then(a=>a.json()).then(a=>{a.success?(a.data.message&&(document.getElementById("currentAnnouncement").value=a.data.message),a.data.en&&(document.getElementById("enAnnouncement").value=a.data.en),a.data.ja&&(document.getElementById("jaAnnouncement").value=a.data.ja),a.data.fr&&(document.getElementById("frAnnouncement").value=a.data.fr),a.data.persistent?document.getElementById("persistentAnnouncement").value="true":
document.getElementById("persistentAnnouncement").value="false"):"AUTH_ERROR"==a.error?newError("You don't seem to be correctly logged in"):newError("An error occured")})}var messagesQueue=[],currentIndex=1;
async function newInfo(a){console.log(a);messagesQueue.push(a);let c=messagesQueue.length,d=setInterval(function(){if(currentIndex==c){var b=document.createElement("p");b.setAttribute("class","info");b.innerText=String(a);document.getElementsByTagName("body")[0].appendChild(b);setTimeout(function(){b.classList.add("show")},100);setTimeout(function(){b.classList.remove("show");currentIndex+=1},5100);clearInterval(d)}},100)}
async function newSuccess(a){console.log(a);messagesQueue.push(a);let c=messagesQueue.length,d=setInterval(function(){if(currentIndex==c){var b=document.createElement("p");b.setAttribute("class","success");b.innerText=String(a);document.getElementsByTagName("body")[0].appendChild(b);setTimeout(function(){b.classList.add("show")},100);setTimeout(function(){b.classList.remove("show");currentIndex+=1},5100);clearInterval(d)}},100)}
async function newError(a){console.error(a);messagesQueue.push(a);let c=messagesQueue.length,d=setInterval(function(){if(currentIndex==c){var b=document.createElement("p");b.setAttribute("class","error");b.innerText=String(a);document.getElementsByTagName("body")[0].appendChild(b);setTimeout(function(){b.classList.add("show")},100);setTimeout(function(){b.classList.remove("show");currentIndex+=1},5100);clearInterval(d)}},100)};
