name: Production Compiling

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Delete current production branch
          uses: dawidd6/action-delete-branch@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branches: production
        
        - name: Creating production branch
          uses: peterjgrainger/action-create-branch@v2.0.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            branch: 'production'

        - uses: actions/checkout@v2
          with:
            ref: production
                
        - name: Installing Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'

        - name: Display Python version
          run: python -c "import sys; print(sys.version)"

        - name: Installing dependencies
          run: pip install beautifulsoup4 htmlmin

        - name: Making temp production dir
          run: mkdir production

        - name: Compiling HTML
          run: python compilers/compile_html.py

        - name: Compiling CSS
          run: python compilers/compile_css.py

        - name: Installing Node 14.16
          uses: actions/setup-node@v1
          with:
            node-version: '14.16'
        
        - name: Installing dependencies
          run: npm install --save-dev postcss postcss-cli autoprefixer cssnano postcss-preset-env google-closure-compiler

        - name: PostCSS
          run: npx postcss production/main.css -o production/main.css

        - name: Compiling JS
          run: |
            npx google-closure-compiler --js='scripts/**.js' --js='!scripts/login.js' --js_output_file 'production/main.js'
            npx google-closure-compiler --js='scripts/login.js' --js_output_file 'production/login.js'

        - name: Deleting unnecessary files
          run: |
            rm -r experimental
            rm -r scripts
            rm -r styles
            rm .gitignore
            rm index.html
            rm login.html
            rm postcss.config.js
        
        - name: Reorganizing Repo
          run: |
            mkdir styles
            mkdir scripts
            mv production/index.html .
            mv production/login.html .
            python compilers/copy_files.py
            rm -r compilers
            rm -r production

        - name: Pusing the results
          run: |
            git config --global user.name 'Animenosekai'
            git config --global user.email '40539549+Animenosekai@users.noreply.github.com'
            git commit -am "[build] Production Build"
            git push